import http from 'http';
import { readFile } from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const staticFiles = {
  '/': 'public/index.html',
  '/app.js': 'public/app.js',
  '/styles.css': 'public/styles.css'
};

const conversationStarter = {
  templateType: 'conversation_starter',
  text: "Hi, I'm your virtual assistant. How can I assist you? Here are conversation starters which you can select to start a conversation or ask a question.",
  questions: [
    'What are the key features of your product?',
    'How can I get started?',
    'Tell me about pricing options',
    'What integrations do you support?'
  ],
  disclaimer: 'Generated by AI'
};

function buildModelResponse(message, templateType = 'followup') {
  const normalized = message.toLowerCase();

  if (normalized.includes('pricing')) {
    return {
      templateType,
      text: 'We offer flexible pricing plans tailored to your needs. Our basic plan starts at $29/month, professional at $79/month, and enterprise solutions with custom pricing.',
      questions: [
        "What's included in the professional plan?",
        'Tell me about the enterprise option',
        'Do you offer a free trial?'
      ],
      disclaimer: 'Generated by AI'
    };
  }

  if (normalized.includes('professional')) {
    return {
      templateType,
      text: 'The professional plan includes advanced analytics, priority support, unlimited team members, custom integrations, and access to all premium features. You also get dedicated account management and quarterly business reviews.',
      questions: [],
      disclaimer: 'Generated by AI'
    };
  }

  if (normalized.includes('integration')) {
    return {
      templateType,
      text: 'We integrate with major CRM, support, and collaboration tools including Salesforce, HubSpot, Zendesk, Jira, Slack, and Microsoft Teams. We also provide webhooks and REST APIs for custom integrations.',
      questions: ['Can you share API docs?', 'Do you support SSO?', 'How fast is onboarding?'],
      disclaimer: 'Generated by AI'
    };
  }

  if (normalized.includes('start')) {
    return {
      templateType,
      text: 'Getting started is simple: create an account, complete your workspace profile, connect one integration, and run the onboarding checklist. Most teams are live in less than 30 minutes.',
      questions: ['Can you guide me through setup?', 'Is there a free trial?', 'Do you offer implementation support?'],
      disclaimer: 'Generated by AI'
    };
  }

  return {
    templateType,
    text: 'Absolutely. I can help with product capabilities, pricing, onboarding, integrations, and best practices. Tell me what you want to explore first.',
    questions: ['Show pricing options', 'Explain key features', 'Help me get started'],
    disclaimer: 'Generated by AI'
  };
}

function sendSseEvent(res, payload) {
  res.write(`data: ${JSON.stringify(payload)}\n\n`);
}

async function handleStream(req, res) {
  let body = '';
  req.on('data', (chunk) => {
    body += chunk;
  });

  req.on('end', async () => {
    const parsedBody = body ? JSON.parse(body) : {};
    const { message = '', templateType = 'followup' } = parsedBody;
    const response = buildModelResponse(message, templateType);

    res.writeHead(200, {
      'Content-Type': 'text/event-stream',
      'Cache-Control': 'no-cache, no-transform',
      Connection: 'keep-alive',
      'X-Accel-Buffering': 'no'
    });

    sendSseEvent(res, { type: 'message_start', templateType: response.templateType });

    const words = response.text.split(' ');
    for (let i = 0; i < words.length; i += 3) {
      const delta = `${words.slice(i, i + 3).join(' ')} `;
      sendSseEvent(res, { type: 'text_delta', delta });
      await new Promise((resolve) => setTimeout(resolve, 80));
    }

    sendSseEvent(res, { type: 'questions', items: response.questions });
    sendSseEvent(res, { type: 'disclaimer', text: response.disclaimer });
    sendSseEvent(res, { type: 'message_done' });
    res.end();
  });
}

const server = http.createServer(async (req, res) => {
  if (req.method === 'GET' && req.url === '/api/conversation-starter') {
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify(conversationStarter));
    return;
  }

  if (req.method === 'POST' && req.url === '/api/chat/stream') {
    handleStream(req, res);
    return;
  }

  if (req.method === 'GET' && staticFiles[req.url]) {
    try {
      const filePath = path.join(__dirname, staticFiles[req.url]);
      const file = await readFile(filePath);
      const contentType = req.url.endsWith('.js')
        ? 'text/javascript'
        : req.url.endsWith('.css')
          ? 'text/css'
          : 'text/html';

      res.writeHead(200, { 'Content-Type': contentType });
      res.end(file);
    } catch {
      res.writeHead(404);
      res.end('Not found');
    }
    return;
  }

  res.writeHead(404);
  res.end('Not found');
});

const port = process.env.PORT || 3000;
server.listen(port, () => {
  console.log(`Server running on http://localhost:${port}`);
});
