import http from 'http';
import { readFile } from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const staticFiles = {
  '/': 'public/index.html',
  '/app.js': 'public/app.js',
  '/styles.css': 'public/styles.css'
};

const conversationStarter = {
  templateType: 'conversation_starter',
  text: "Hi, I'm your virtual assistant. How can I assist you? Here are conversation starters which you can select to start a conversation or ask a question.",
  questions: [
    'What are the key features of your product?',
    'How can I get started?',
    'Tell me about pricing options',
    'Show me a big message example with HTML'
  ],
  disclaimer: 'Generated by AI'
};

function buildModelResponse(message, templateType = 'followup') {
  const normalized = message.toLowerCase();

  if (normalized.includes('big message') || normalized.includes('html')) {
    return {
      templateType,
      text: `<p>Great request — here is a <strong>large streamed HTML message</strong> to validate smooth rendering.</p><p>Our assistant can stream long form responses that include <em>rich formatting</em>, lists, and links while preserving typing flow.</p><ul><li><strong>Step 1:</strong> Create your workspace and invite teammates.</li><li><strong>Step 2:</strong> Connect integrations like Slack, Salesforce, and Jira.</li><li><strong>Step 3:</strong> Configure policies, knowledge bases, and answer tone.</li></ul><p>For API teams, use <code>POST /api/chat/stream</code> and render chunk deltas in the browser with a frame-based update queue. This avoids janky paint and makes streaming feel natural and continuous.</p><p>You can also safely support basic HTML tags from trusted sources in streamed output: <code>p, strong, em, ul, li, code, a</code>.</p><p><a href="https://example.com/docs" target="_blank" rel="noopener noreferrer">Read implementation docs</a> and continue testing with long prompts.</p>`,
      questions: [
        'Can you stream markdown too?',
        'How do I sanitize HTML from untrusted models?',
        'Show me a 3-paragraph onboarding script',
        'How can I reduce first token latency?'
      ],
      disclaimer: 'Generated by AI'
    };
  }

  if (normalized.includes('pricing')) {
    return {
      templateType,
      text: '<p>We offer flexible pricing plans tailored to your needs. Basic starts at <strong>$29/month</strong>, Professional at <strong>$79/month</strong>, and Enterprise pricing is custom.</p>',
      questions: [
        "What's included in the professional plan?",
        'Tell me about the enterprise option',
        'Do you offer a free trial?'
      ],
      disclaimer: 'Generated by AI'
    };
  }

  if (normalized.includes('professional')) {
    return {
      templateType,
      text: '<p>The Professional plan includes advanced analytics, priority support, unlimited team members, custom integrations, and premium features.</p><p>You also get dedicated account management and quarterly business reviews.</p>',
      questions: [],
      disclaimer: 'Generated by AI'
    };
  }

  if (normalized.includes('integration')) {
    return {
      templateType,
      text: '<p>We integrate with Salesforce, HubSpot, Zendesk, Jira, Slack, and Microsoft Teams. We also provide webhooks and REST APIs for custom integrations.</p>',
      questions: ['Can you share API docs?', 'Do you support SSO?', 'How fast is onboarding?'],
      disclaimer: 'Generated by AI'
    };
  }

  if (normalized.includes('start')) {
    return {
      templateType,
      text: '<p>Getting started is simple: create an account, complete workspace setup, connect one integration, and run the onboarding checklist.</p><p>Most teams are live in less than 30 minutes.</p>',
      questions: ['Can you guide me through setup?', 'Is there a free trial?', 'Do you offer implementation support?'],
      disclaimer: 'Generated by AI'
    };
  }

  return {
    templateType,
    text: '<p>Absolutely. I can help with product capabilities, pricing, onboarding, integrations, and best practices. Tell me what you want to explore first.</p>',
    questions: ['Show pricing options', 'Explain key features', 'Show me a big message example with HTML'],
    disclaimer: 'Generated by AI'
  };
}

function sendSseEvent(res, payload) {
  res.write(`data: ${JSON.stringify(payload)}\n\n`);
}

function wait(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function streamHtmlDeltas(res, html) {
  let cursor = 0;
  while (cursor < html.length) {
    const size = Math.max(1, Math.floor(Math.random() * 5) + 2);
    const delta = html.slice(cursor, cursor + size);
    sendSseEvent(res, { type: 'text_delta', delta, format: 'html' });
    cursor += size;
    await wait(20);
  }
}

async function streamQuestions(res, questions) {
  for (const question of questions) {
    sendSseEvent(res, { type: 'question_start' });
    for (let i = 0; i < question.length; i += 4) {
      sendSseEvent(res, { type: 'question_delta', delta: question.slice(i, i + 4) });
      await wait(16);
    }
    sendSseEvent(res, { type: 'question_done' });
  }
}

async function handleStream(req, res) {
  let body = '';
  req.on('data', (chunk) => {
    body += chunk;
  });

  req.on('end', async () => {
    const parsedBody = body ? JSON.parse(body) : {};
    const { message = '', templateType = 'followup' } = parsedBody;
    const response = buildModelResponse(message, templateType);

    res.writeHead(200, {
      'Content-Type': 'text/event-stream',
      'Cache-Control': 'no-cache, no-transform',
      Connection: 'keep-alive',
      'X-Accel-Buffering': 'no'
    });

    sendSseEvent(res, { type: 'message_start', templateType: response.templateType, format: 'html' });
    await streamHtmlDeltas(res, response.text);
    await streamQuestions(res, response.questions);
    sendSseEvent(res, { type: 'disclaimer', text: response.disclaimer });
    sendSseEvent(res, { type: 'message_done' });
    res.end();
  });
}

const server = http.createServer(async (req, res) => {
  if (req.method === 'GET' && req.url === '/api/conversation-starter') {
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify(conversationStarter));
    return;
  }

  if (req.method === 'POST' && req.url === '/api/chat/stream') {
    handleStream(req, res);
    return;
  }

  if (req.method === 'GET' && staticFiles[req.url]) {
    try {
      const filePath = path.join(__dirname, staticFiles[req.url]);
      const file = await readFile(filePath);
      const contentType = req.url.endsWith('.js')
        ? 'text/javascript'
        : req.url.endsWith('.css')
          ? 'text/css'
          : 'text/html';

      res.writeHead(200, { 'Content-Type': contentType });
      res.end(file);
    } catch {
      res.writeHead(404);
      res.end('Not found');
    }
    return;
  }

  res.writeHead(404);
  res.end('Not found');
});

const port = process.env.PORT || 3000;
server.listen(port, () => {
  console.log(`Server running on http://localhost:${port}`);
});
